// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('c:/Users/sstep/Documents/Software Development/Dissertation Project/source_code/GrowWell/client/node_modules/react');
var { Component } = React;
var ReactNative = require('c:/Users/sstep/Documents/Software Development/Dissertation Project/source_code/GrowWell/client/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('client', appParameters);
});
require('c:/Users/sstep/Documents/Software Development/Dissertation Project/source_code/GrowWell/client/index.js');